# Generated by Django 6.0.3 on 2026-04-12 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_herocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcard',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_cards/'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
