# Generated by Django 6.0.3 on 2026-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_reviewcard_profile_image_reviewcard_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviewcard',
            name='tag',
        ),
    ]
