# Generated by Django 6.0.3 on 2026-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_reviewspagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal/admin name for this version, e.g. 'Spring FAQs'.", max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name if left blank.', max_length=140, unique=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the title.', max_length=120)),
                ('title', models.CharField(help_text='Main heading for the FAQ section.', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text below the title.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one FAQ page content entry should usually be active.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in admin ordering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Page Content',
                'verbose_name_plural': 'FAQ Page Content',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_faq_page_content')],
            },
        ),
    ]
