# Generated by Django 6.0.3 on 2026-04-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_faqpagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'FAQ Category', 'verbose_name_plural': 'FAQ Categories'},
        ),
    ]
