# Generated by Django 6.0.3 on 2026-04-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_alter_faqcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'FAQ Question', 'verbose_name_plural': 'FAQ Questions'},
        ),
    ]
