# Generated by Django 6.0.3 on 2026-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero/background image for the FAQs page.', null=True, upload_to='faqs/hero/'),
        ),
    ]
