# Generated by Django 6.0.3 on 2026-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_gallerypagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero/background image for the gallery page.', null=True, upload_to='gallery/hero/'),
        ),
    ]
