# Generated by Django 6.0.3 on 2026-04-13 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_alter_gallerypagecontent_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text="Frontend icon key (e.g. 'scissors', 'wind')", max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIncludedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryIncludedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_included_items', to='marketing.servicecategory')),
                ('included_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_included_items', to='marketing.serviceincludeditem')),
            ],
            options={
                'ordering': ['sort_order', 'included_item__name'],
            },
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='included_items',
            field=models.ManyToManyField(blank=True, related_name='service_categories', through='marketing.ServiceCategoryIncludedItem', to='marketing.serviceincludeditem'),
        ),
        migrations.AddIndex(
            model_name='servicecategoryincludeditem',
            index=models.Index(fields=['service_category', 'sort_order'], name='marketing_s_service_bfc845_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategoryincludeditem',
            index=models.Index(fields=['included_item'], name='marketing_s_include_424f27_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecategoryincludeditem',
            constraint=models.UniqueConstraint(fields=('service_category', 'included_item'), name='unique_included_item_per_service_category'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['sort_order'], name='marketing_s_sort_or_94f2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_published'], name='marketing_s_is_publ_8e3207_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_published', 'sort_order'], name='marketing_s_is_publ_998aa0_idx'),
        ),
    ]
