# Generated by Django 6.0.3 on 2026-04-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_servicecategory_serviceincludeditem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Service Page Category', 'verbose_name_plural': 'Service Page Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicecategoryincludeditem',
            options={'ordering': ['sort_order', 'included_item__name'], 'verbose_name': 'Service Page Category', 'verbose_name_plural': 'Service Page Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceincludeditem',
            options={'ordering': ['name'], 'verbose_name': 'Service Page Item', 'verbose_name_plural': 'Service Page Items'},
        ),
    ]
