# Generated by Django 6.0.3 on 2026-04-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_galleryphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery Photos'},
        ),
    ]
