# Generated by Django 6.0.3 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_alter_galleryphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal/admin name, e.g. 'Default Homepage Hero'.", max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name if left blank.', max_length=140, unique=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the title.', max_length=120)),
                ('title', models.CharField(help_text='Main hero heading.', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text under the title.')),
                ('expect_item_1', models.CharField(blank=True, help_text="First 'What you can expect' item.", max_length=160)),
                ('expect_item_2', models.CharField(blank=True, help_text="Second 'What you can expect' item.", max_length=160)),
                ('expect_item_3', models.CharField(blank=True, help_text="Third 'What you can expect' item.", max_length=160)),
                ('hero_video', models.FileField(blank=True, help_text='Optional hero video. If empty, frontend will fallback to images or hide media section.', null=True, upload_to='home/hero/videos/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one homepage hero content entry should be active.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in admin ordering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero Content',
                'verbose_name_plural': 'Homepage Hero Content',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_homepage_hero_content')],
            },
        ),
    ]
