# Generated by Django 6.0.3 on 2026-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_homepageherocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/about_features/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage About Module',
                'verbose_name_plural': 'Homepage About Modules',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
