# Generated by Django 6.0.3 on 2026-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_aboutmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/about_modules/'),
        ),
    ]
