# Generated by Django 6.0.3 on 2026-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_alter_aboutmodule_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcard',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Reviews Page Review Card', 'verbose_name_plural': 'Reviews Page Review Cards'},
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='If enabled, this review can be displayed on the homepage.'),
        ),
    ]
