# Generated by Django 6.0.3 on 2026-04-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_alter_reviewcard_options_reviewcard_show_on_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcard',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Review Card', 'verbose_name_plural': 'Review Cards'},
        ),
    ]
