# Generated by Django 6.0.3 on 2026-04-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_alter_reviewcard_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureCard',
        ),
        migrations.DeleteModel(
            name='HeroCard',
        ),
    ]
