# Generated by Django 6.0.3 on 2026-04-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_delete_featurecard_delete_herocard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroContent',
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
