# Generated by Django 6.0.3 on 2026-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_delete_herocontent_reviewcard_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcard',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
