# Generated by Django 6.0.3 on 2026-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_alter_reviewcard_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageherocontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional hero image shown at the top of the homepage content.', null=True, upload_to='home/hero/images/'),
        ),
    ]
