# Generated by Django 6.0.3 on 2026-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_homepageherocontent_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='show_on_homepage',
        ),
    ]
