# Generated by Django 6.0.3 on 2026-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_remove_galleryphoto_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
