# Generated by Django 5.2.12 on 2026-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Keep this short and punchy for the website service card.', max_length=300),
        ),
    ]
