# Generated by Django 6.0.3 on 2026-03-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
