# Generated by Django 6.0.3 on 2026-03-26 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text="Frontend icon key (e.g. 'scissors', 'wind')", max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['sort_order'], name='services_se_sort_or_ac189b_idx'), models.Index(fields=['is_published'], name='services_se_is_publ_408e3e_idx'), models.Index(fields=['is_published', 'sort_order'], name='services_se_is_publ_1a63f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceIncludedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='services.servicecategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['service', 'sort_order'], name='services_se_service_e9cad8_idx')],
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='unique_service_included_item')],
            },
        ),
    ]
