# Generated by Django 6.0.3 on 2026-03-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceincludeditem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='services.servicecategory'),
        ),
    ]
