# Generated by Django 6.0.3 on 2026-03-26 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceincludeditem_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryIncludedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'included_item__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='serviceincludeditem',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='serviceincludeditem',
            name='unique_service_included_item',
        ),
        migrations.RemoveIndex(
            model_name='serviceincludeditem',
            name='services_se_service_e9cad8_idx',
        ),
        migrations.AlterField(
            model_name='serviceincludeditem',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategoryincludeditem',
            name='included_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_included_items', to='services.serviceincludeditem'),
        ),
        migrations.AddField(
            model_name='servicecategoryincludeditem',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_included_items', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='included_items',
            field=models.ManyToManyField(blank=True, related_name='service_categories', through='services.ServiceCategoryIncludedItem', to='services.serviceincludeditem'),
        ),
        migrations.RemoveField(
            model_name='serviceincludeditem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceincludeditem',
            name='sort_order',
        ),
        migrations.AddIndex(
            model_name='servicecategoryincludeditem',
            index=models.Index(fields=['service_category', 'sort_order'], name='services_se_service_8669a1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategoryincludeditem',
            index=models.Index(fields=['included_item'], name='services_se_include_d11c24_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecategoryincludeditem',
            constraint=models.UniqueConstraint(fields=('service_category', 'included_item'), name='unique_included_item_per_service_category'),
        ),
    ]
