# Generated by Django 6.0.3 on 2026-04-17 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        ('marketing', '0027_delete_herocontent_reviewcard_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number for follow-up', max_length=20)),
                ('service_category_title', models.CharField(blank=True, help_text='Snapshot of the selected service category title at submission time.', max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(blank=True, help_text='Selected service category for this quote request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='marketing.servicecategory')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='inbox_quote_created_af70e2_idx'), models.Index(fields=['service_category'], name='inbox_quote_service_d6bcd4_idx')],
            },
        ),
    ]
