# Generated by Django 6.0.3 on 2026-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='address',
            field=models.CharField(blank=True, help_text='Optional service address.', max_length=255),
        ),
    ]
