# Generated by Django 6.0.3 on 2026-04-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aboutsection_id_alter_homepage_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
