# Generated by Django 6.0.3 on 2026-04-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_aboutsection_delete_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
