# Generated by Django 6.0.3 on 2026-04-13 21:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('service_area', models.CharField(blank=True, help_text='Example: Bloomington, IN and surrounding areas', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('google_business_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#013220', help_text='Main brand color in hex format, e.g. #013220', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in the format #RRGGBB.', regex='^#(?:[0-9A-Fa-f]{6})$')])),
                ('secondary_color', models.CharField(default='#ada18c', help_text='Secondary brand color in hex format, e.g. #ada18c', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in the format #RRGGBB.', regex='^#(?:[0-9A-Fa-f]{6})$')])),
                ('highlight_color', models.CharField(default='#c49c48', help_text='Highlight color in hex format, e.g. #c49c48', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in the format #RRGGBB.', regex='^#(?:[0-9A-Fa-f]{6})$')])),
                ('text_color', models.CharField(default='#000000', help_text='Default text color in hex format, e.g. #000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in the format #RRGGBB.', regex='^#(?:[0-9A-Fa-f]{6})$')])),
                ('text_inverse_color', models.CharField(default='#ffffff', help_text='Inverse text color in hex format, e.g. #ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in the format #RRGGBB.', regex='^#(?:[0-9A-Fa-f]{6})$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: "Mon - Fri", "Saturday", "Sunday"', max_length=100)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
