# Generated by Django 6.0.3 on 2026-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main website logo used in the navbar and branding.', null=True, upload_to='site/'),
        ),
    ]
