# Generated by Django 6.0.3 on 2026-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Default description used for search engines and social sharing.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_image',
            field=models.ImageField(blank=True, help_text='Image used for search engines and social sharing. Recommended size: 1200x630 pixels.', null=True, upload_to='site/seo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Default title used for search engines and social sharing.', max_length=255),
        ),
    ]
