# Generated by Django 6.0.3 on 2026-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_seo_description_sitesettings_seo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Default description used for search engines (Google) and social sharing.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_image',
            field=models.ImageField(blank=True, help_text='Image used for search engines (Google) and social sharing. Recommended size: 1200x630 pixels.', null=True, upload_to='site/seo/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Default title used for search engines (Google) and social sharing.', max_length=255),
        ),
    ]
